### ISSUE TITLE
ебучая flash

### ISSUE THREAD

**Issue by Srankl1n** [animusdev/whiTGreen#108]
сука эта хуйня станит 3 на 3 и даже кликать по персу не надо

**Comment by HalilDaBlack** [comment]
Так и надо

**Comment by Seldorne** [comment]
Поддерживаю. 3х3 - ослепление. Клик - стан.

**Comment by jammer312** [comment]
Из проголосовавших двое за (сранклин и селдорн), двое против (HalilDaBlack и голиаф в дискордоконфе ваета, которому лень было регаться тут, поэтому он через слап меня выразил свое мнение), так что пока остается так, как есть.
