### ISSUE TITLE
малфанутый ИИ

### ISSUE THREAD

**Issue by Srankl1n** [animusdev/whiTGreen#136]
вы че реально ебанутые такие фичи оставлять/делать?

>малф ии может делать венты/камеры/шлюзы/консоли/етс электронника МОБАМИ

**Comment by Seldorne** [comment]
Их всего восемь-десять штук может быть или чуть больше.

**Comment by jammer312** [comment]
На самом деле больше, но не чуть. Лень лазить по коду, но вроде у малфа очков всего 100, они невосстановимы, на одну покупку этой способности, равную трем использованиям, уходит 15. Т.е. всего 18 использований, причем мобы не блистают робастностью и неубиваемостью, так что оно вполне сбалансировано.
Если приведешь единомышленников, которые играют на сборке и считают фичу лишней, переоткрывай этот иссуй и отписывайтесь тут. До тех пор (если вдруг) закрою, чтоб среди активных не висело.
