### ISSUE TITLE
Разобрал пол - лестница упала

### ISSUE THREAD

**Issue by joctopus** [animusdev/whiTGreen#14]
сабж. Разобрал пол РЦД - лестница упала внизу, наверх никак.
Надо сделать лестницу НЕПАДАЮЩЕЙ.

**Comment by joctopus** [comment]
Так же помимо лестницы падают и трубы. А провода не падают.

**Comment by Dark-Magov** [comment]
С какого хуя у тебя лестница будет нападающей если она крепится к люку в полу?
А за трубы по шаманю.

**Comment by ucnaHez** [comment]
Ну просто выглядит странно, когда два куска одной лестницы лежат внизу, она же как бэ цельная скрепленная.

**Comment by Dark-Magov** [comment]
Это тоже поправлю, как-раз собирался.

**Comment by Dark-Magov** [comment]
> Так же помимо лестницы падают и трубы. А провода не падают.

> А за трубы по шаманю.

После длительных размышлений ~~и выкуривания физики и сопромата~~ я пришёл к выводу что падение проводов забагалось, а трубы и должны падать.

**Comment by ucnaHez** [comment]
Как трубы будут падать? Они же приделаны за края, на луне вон вообще в космосе висели.

**Comment by Dark-Magov** [comment]
В космосе пусть и дальше висят, там гравитации нет.
А падать будут потому что не выдерживают своего веса.

**Comment by Dark-Magov** [comment]
Во-первых - шестиметровую над двухметровой.
Во-вторых - зависит от трубы

**Comment by ucnaHez** [comment]
>шестиметровую

Почитай desc трубы

>зависит от трубы

Если она не картоннобумажная (даже если да) он не сломается хоть как, если не прыгать на ней офкоз

**Comment by Dark-Magov** [comment]
> Почитай desc трубы

Спасибо что напомнил, сейчас пофикшу.

> Если она не картоннобумажная (даже если да) он не сломается хоть как, если не прыгать на ней офкоз

Вот не верю что горизонтальная труба без поддержки и под нагрузкой так уж много выдержит.

**Comment by Dark-Magov** [comment]
> ты чо ты чо, тайлы метр на метр на два не трожь
Два на два на два. ~~посмотри в описание проводки.~~
**УУУУУУ ПИДРИЛЫ БЛЯ, ОПИСАНИЕ ПРОВОДОВ ПОМЕНЯЛИ.**
Ща уйду и пофикшу трубы в отместку.

> она же маленького сечения, чо ей не выдерживать
Рука твоя маленькое сечение.

**Comment by ucnaHez** [comment]
Но эти трубы реально не сильно толстые, в руку взять можно
как газовая труба, как по мне

>поменяли описание проводов

Можешь историю посмотреть, никто ничего не менял

**Comment by NazarFogmann** [comment]
Объем трубы- 70 литров
Тайл 2 на 2 метра

**Comment by NazarFogmann** [comment]
Устроили тут цирк из-за хуйни.
Трубы должны падать и провода тоже
