### ISSUE TITLE
гостфолов

### ISSUE THREAD

**Issue by Srankl1n** [animusdev/whiTGreen#141]
если начать фолловить кого-то одного, потом начать фолловить кого-то другого, то если кто-то первый двинется то ты к нему джампаешься и начинаешь фолловить, при том если другой начинает двигаться то ничего не происходит

**Comment by jammer312** [comment]
Уже репортнули и вон даже фикс висит #139 .

**Comment by Srankl1n** [comment]
а, ну ок
