### ISSUE TITLE
После разрушения меха не появляются обломки

### ISSUE THREAD

**Issue by ostpolkhan** [animusdev/whiTGreen#145]

**Comment by jammer312** [comment]
Вроде же появлялись.

**Comment by ostpolkhan** [comment]
Когда Рипли на шаттле сломал ничего не появилось

**Comment by jammer312** [comment]
Вечером на локалке проверю, пофикшу, если получится повторить.

**Comment by jammer312** [comment]
![Все работает](https://i.imgur.com/N35fmmd.png)
Не знаю, как получилось, что у тебя не появились обломки. Пока закрываю, если вдруг еще раз проявится, переоткрывай и постарайся как можно точнее описать, как оно вообще получилось.
