### ISSUE TITLE
Невидимость не работает

### ISSUE THREAD

**Issue by ostpolkhan** [animusdev/whiTGreen#154]
С геном невидимости спрайт не пропадает, а становиться лишь чуть-чуть прозрачным

**Comment by HalilDaBlack** [comment]
Ста процентов альфы нет, ну.

**Comment by ostpolkhan** [comment]
Спрайт же пропасть должен после нескольких секунд не двигаясь

**Comment by Srankl1n** [comment]
старый баг старотг, если есть 2 хамелеонника то они будут полупрозрачные
