### ISSUE TITLE
Сделать большую часть вещей разрушаемыми

### ISSUE THREAD

**Issue by joctopus** [animusdev/whiTGreen#16]
Шлюзы etc

**Comment by ucnaHez** [comment]
Ноунихтнайн ты что ебанулся
Здоровый железный шлюз против давлений космоса ломают какой-нить херней типа острого костяного рукомеча или двуручного топора

Это КОНСТРУКЦИЯ, есть инструменты - разбери, нету - сиди и кукарекай, чтобы разобрал кто еще.

**Comment by jammer312** [comment]
Ну так то прочным конструкциям просто накинуть резистов. Сейчас оные шлюзы даже боевой мех могучим пинком не поцарапает. Хотя те же стены (которые по идее прочнее) вполне может.

**Comment by koghs** [comment]
Таки да, запилите через порог урона или хотя бы мехам. А то это говно прочнее стен, даже когда от станции ничего не остается стоят эти шлюзы аки неуязвимые монолиты.

**Comment by ucnaHez** [comment]
Чойта стены прочнее? Стены просто куски железа, а шлюзы имеют структуру, внутри всякие ребра жесткости и прочия болты.

Шлюз как бы вход, тому он обычно куда прочнее и толще и как бы это сказать СТРУКТУРНЕЙ, крепче внутри

А мехос вполне может дрелью расхуярить дверь.

**Comment by Dark-Magov** [comment]
> Чойта стены прочнее? Стены просто куски железа, а шлюзы имеют структуру, внутри всякие ребра жесткости и прочия болты.

Кхм. Стена не кусок железа. Стена те самые рёбра жёсткости на которые сверху повесили пару-другую кусков листового металла.

**Comment by HalilDaBlack** [comment]
Шлюзы как минимум сделаны из того же материала что и стены, постоянно держать давление != держать высокоэнергитические пульки или удары острыми, тяжелыми предметами.

**Comment by ucnaHez** [comment]
>острыми предметами
>пульки

А теперь возьми даже обычную  хлипкую железную квартирную дверь и попробуй сломать ее ПУЛЯМИ или ТОПОРОМ.

Несомненно очень сильные удары дверь вынесут, только это должны быть сильные удары чем-то ну ОЧЕНЬ большим. Пожарного топора явно не хватит.

У нас на станции практически нету чего-то настолько большого чем можно сильно бить, кроме разве что отбойного молотка.

**Comment by ucnaHez** [comment]
>Кхм. Стена не кусок железа. Стена те самые рёбра жёсткости на которые сверху повесили пару-другую кусков листового металла.

Ну сравни просто раму, на которой висит лист митола, и шлюз, который _ря как это описать_ большой тяжелый сложный механизм огроменная дверь для защиты от космома видил когда-нибудь дверь на подлодке расчеты жесткие замки

**Comment by HalilDaBlack** [comment]
Ну тогда и мехов неломаемыми делай, hoole, там же броня висит, тот же ФФ стоит как три укреплённые стенки.

**Comment by Dark-Magov** [comment]
> Ну сравни просто раму, на которой висит лист митола, и шлюз, который ря как это описать большой тяжелый сложный механизм огроменная дверь для защиты от космома видил когда-нибудь дверь на подлодке расчеты жесткие замки
Видел, я  таки скажу что та дверь с подлодки проще "сломается" чем обшивка аналогичной(или даже большей) толщины.

Алсо я не сравнивал раму с шлюзом. Я утверждал что стена не кусок метала.

**Comment by koghs** [comment]
Даже если предположить что шлюз прочнее двери (таки в космических реалиях так наверное и есть) то тут все упирается в банальную логику. Просто сам по себе абсурден тот факт что сделать дыру в стене проще чем вскрыть дверь.

**Comment by Dark-Magov** [comment]
Ну
~~Усложним ломание стенок?~~
Внезапно, при наличии нужных инструментов в ИРЛ стену снести тоже проще чем взломать дверь.
Другое дело что ИРЛ кувалды в каждом втором коридоре не валяются.

**Comment by ucnaHez** [comment]
Ну так и у нас тут тяжелые инструменты не валяются где попало
Я бы даже сказал их нету

Реальные инструменты, которыми ИРЛ можно вынести любую стену или дверь - всякие кувалды, гидравлические ножницы и автогены на станции вообще не представлены.
_а дверь с подлодки (как и шлюз на какой-нить МКС) вынести инструментами вообще не представляется возможным, как по мне, кувалдой его даже не помнешь, автогеном не прорежешь - космические технологии всежтаки_

>Внезапно, при наличии нужных инструментов в ИРЛ стену снести тоже проще чем взломать дверь

И я о том, дверь как бы точка входа, тому крепче.

В ССке тоже все разделено. Есть инструменты точные - идешь в дверь (отвертка мультитул), нет инструментов точных - ломаешь стену (сварка ключ гаечный). Нет вообще инструментов - LEMEETKA, ну нет таких реально тяжелых и с возможностью сильного удара вещей, которыми можно вынести две^Wшлюз.

**Comment by Dark-Magov** [comment]
а как-же синга?

Кинул сингой в шлюз@шлюз вынесен.

**Comment by Dark-Magov** [comment]
В конечнём счёте, считаю что по результатам обсуждения:

**Comment by Dark-Magov** [comment]
Так пожалуй покоректнее будет?

**Comment by ucnaHez** [comment]
Да вонтфикс нормально

**Comment by joctopus** [comment]
Решено. Закрыто.
