### ISSUE TITLE
у квертиона доступ к репе

### ISSUE THREAD

**Issue by Srankl1n** [animusdev/whiTGreen#186]
no god please no

**Comment by jammer312** [comment]
Нету же.

**Comment by PlinHost** [comment]
У жоктопуса доступ к репе, но живем же как-то.

**Comment by ZLOFENIX** [comment]
Каждый день по 20 бекдуров вычищаем, еще 30 не находим.

**Comment by joctopus** [comment]
Ниче ты не вычищаешь. Самое вкусное глубже.
