### ISSUE TITLE
Убрать бомжатню с карты.

### ISSUE THREAD

**Issue by Xodok** [animusdev/whiTGreen#195]
Раньше это казалось хорошей штукой, но сейчас при наличии стольких подвалов и техов, обустроить бомжатню хоть на мостике не составляет труда. Плюс бомжи это кочевой народ, сваливающий от мусоров прыгая со станции на станцию, так что подготовленного жилья для них быть на НАУЧНОЙ СТАНЦИИ ВЫСОКОГО УРОВНЯ  не может. 
Да и вход туда дурацкий, и обсчитывать меньше, когда сбежит синга. Со всех сторон плюсы.

**Comment by FMajesty** [comment]
Пошел нахуй с тупичка.
