### ISSUE TITLE
Руды палятся по наведению курсора

### ISSUE THREAD

**Issue by n0rm4ld3f4ult** [animusdev/whiTGreen#22]
У всех руд на астероиде(кроме железа) отсутствуют спрайты.
![image](https://user-images.githubusercontent.com/33929706/34908450-d13fbdae-f8a0-11e7-9b39-e3f7359cd0eb.png)
![image](https://user-images.githubusercontent.com/33929706/34908454-d48cc416-f8a0-11e7-8a0e-6f71ebcef3a2.png)
Палится только в отображении названия слева снизу.

**Comment by PlinHost** [comment]
Это фича, используй сканер. А палиться наверное не должно.

**Comment by n0rm4ld3f4ult** [comment]
А почему тогда железо видно?

**Comment by ucnaHez** [comment]
Наверное типа баланс.
Железо малоценно, его можешь копать и без сканера, а все остальное изволь сканировать

**Comment by ucnaHez** [comment]
Иссуя превращается в иссую "минералы палятся по наведению курсора"

**Comment by n0rm4ld3f4ult** [comment]
Я думаю, можно банально сменить названия руд
