### ISSUE TITLE
Фальшивое надевание наручников. Микробаги у предложения по улучшению

### ISSUE THREAD

**Issue by Alexs410** [animusdev/whiTGreen#227]
1) Кабельные наручники остаются видны (в виде кабеля в руке) при их применении.
2) Реализовать возможность хотя бы ХОДИТЬ, не теряя маскировку.
3) Видимость того, что человек маскируется. Хоть чтобы через 2-3 тайла уже нельзя было сказать, настоящие ли наручники.

**Comment by jammer312** [comment]
Предлагаю считать закрытым.
