### ISSUE TITLE
Плащи не одеваются в слот Neck

### ISSUE THREAD

**Issue by n0rm4ld3f4ult** [animusdev/whiTGreen#23]
Этим все сказано. Только на спину, заместо рюкзака

**Comment by koghs** [comment]
Странно что еще никто не пошутил про прогнивших разрабов ТГ. 
Раньше плащи носились заместо рюкзаков для того что бы демонстрировать насколько ты крут и не нуждаешься в рюкзаке.

**Comment by n0rm4ld3f4ult** [comment]
А зачем тогда слот neck?

**Comment by jammer312** [comment]
Для галстуков, амулетов, _кобуры детектива_.

**Comment by ucnaHez** [comment]
Фича

Плащ одевается на спину, ибо за крутость платят

На шею бандольерки, жетоны, галстуки, еще чего-то

**Comment by Dark-Magov** [comment]
Ёпт, плащи ж бронированные.
Так что у них и функционал есть.
