### ISSUE TITLE
Контрибутнг гуиде

### ISSUE THREAD

**Issue by ucnaHez** [animusdev/whiTGreen#28]
подогнать, а то там ссылки на гринорепу

**Comment by Dark-Magov** [comment]
А ёпт, ты о другом.

**Comment by ucnaHez** [comment]
Я о том гайде, на который ведет ссылка в ридми

**Comment by ucnaHez** [comment]
>cd green
>animusdev/green
>гринодевтима

**Comment by Dark-Magov** [comment]
Мне сказали о ссылках, я пофиксил ссылки.
