### ISSUE TITLE
МОТД

### ISSUE THREAD

**Issue by ucnaHez** [animusdev/whiTGreen#29]
мотд старый

**Comment by Dark-Magov** [comment]
Ты про [этот](https://github.com/animusdev/whiTGreen/blob/dev/config/motd.txt)?

**Comment by ucnaHez** [comment]
Не, не он

Он же не с билда берется, судя по всему, там пишет так:

Добро пожаловать на White Dream!


В данный момент мы используем /TG/Station13 билд.
This is Russian server and Russian is only one allowed language here. Be sure, that you can speak it, if you willing to play here.





Если вы зашли сюда впервые, не забудьте ознакомиться с этой страничкой на вики.


Правила сервера 


Вы можете найти описания профессий на этой странице или различные руководства на нашей вики.


Вы можете сообщить о найденных вами багах в наш Discord или же по этой ссылке 


Причем ссылки на другую репу и вообще

**Comment by joctopus** [comment]
Неактуально, пофикшено!
