### ISSUE TITLE
Столбик в воздухе висит

### ISSUE THREAD

**Issue by ucnaHez** [animusdev/whiTGreen#30]
![1](https://user-images.githubusercontent.com/9585826/34916723-7d46e826-f95e-11e7-907a-5e71c7652b8c.PNG)

Все остальные хорошо

**Comment by ucnaHez** [comment]
Кстати, не помешали бы еще две камеры в подвале, а то левые поля просматриваются только с камеры внутри

**Comment by ucnaHez** [comment]
И коль уж туда кто полезет, в подвале из места наблюдения за сингой надо убрать эти листы митола, или подвинуть их подальше, а то когда синга на четверке, они стекло бьют.

**Comment by Dark-Magov** [comment]
А что на их место поставить?

**Comment by ucnaHez** [comment]
Просто их отодвинуть чуть подальше, чтобы не втягивало четверкой
