### ISSUE TITLE
Уберите уже дохлую мышь

### ISSUE THREAD

**Issue by ucnaHez** [animusdev/whiTGreen#5]
Дохлая-мышь предмет со спрайтом живой мыши около портретов в центре станции на вентиляционной решетке, откуда она там взялась не ясно, но зачем?

**Comment by Dark-Magov** [comment]
Чтобы у уборщика была работа.

**Comment by ucnaHez** [comment]
Но у дохлой мыши спрайт живой!

**Comment by Dark-Magov** [comment]
joke misses you
