### ISSUE TITLE
Вентиляционная решетка в баре

### ISSUE THREAD

**Issue by ucnaHez** [animusdev/whiTGreen#6]
Справа от самого левого столика, не связана ни с чем, вообще не несет нагрузки

**Comment by Dark-Magov** [comment]
Таки судя по требу над ней - она просто криво повёрнута
![image](https://user-images.githubusercontent.com/17250628/34823572-f9293fa0-f6db-11e7-9f2a-408329f3d187.png)

Я подозреваю что тут может быть не так - завтра пофикшу.

**Comment by ucnaHez** [comment]
Странно
