### ISSUE TITLE
Прогресбары

### ISSUE THREAD

**Issue by Dark-Magov** [animusdev/whiTGreen#64]
![image](https://user-images.githubusercontent.com/17250628/35138284-e812a91c-fcfe-11e7-9075-2d2d03e2c0dc.png)

**Comment by joctopus** [comment]
А почему бы и нет? Не вижу проблемы. Удобная штучка

**Comment by ucnaHez** [comment]
Нахуй надо? Впрочем, если люди аццки страдают, если не видят, что их окно откручивается - чо нет

**Comment by Wyderar** [comment]
> Нахуй надо? 

Хотя бы ради бара при резисте в наручниках.

**Comment by koghs** [comment]
А почему вообще нет? Не все тут боги тайминга, да и с полосочкой тебе сразу становится понятно что действие прервалось и ты не стоишь как идиот ожидая пока наручники отвяжутся/стена проковыряется/окно прикрутится.

**Comment by Seldorne** [comment]
Голосую за. А по поводу >>Нахуй надо? - на хороших билдах они отключаются через преференсы, так что если не понравится, можно убрать с глаз долой.

**Comment by jammer312** [comment]
@ucnaHez Прогрессбары видны только тем, кто выполняет соответствующее действие. Т.е. никто, кроме тебя, не увидит, как ты откручиваешь окно. Ну и таки да, не все тут боги тайминга, да и от лагов никто не защищен.

**Comment by jammer312** [comment]
Запилено.
