### ISSUE TITLE
Точка равновесия синги проёбана

### ISSUE THREAD

**Issue by Dark-Magov** [animusdev/whiTGreen#7]
Ускоритель на нуле выдаёт сингулярности слишком много энергии.

**Comment by ucnaHez** [comment]
Прямо сейчас на сервере в одного поднял сингуло, оставил ускоритель на нуле, проснулся от того, что плитку сорвало и синга на четверке

**Comment by NazarFogmann** [comment]
Консоль могло емпшнуть. Смотрите в эту сторону

**Comment by ucnaHez** [comment]
Какую еще консоль? Тыщщу лет не ЕМПшило, а ща начало? Да и не ЕМПшится она.

Дело явно в мультизэт клонах - ибо ничего не меняли, а раньше она ж не бегала

**Comment by ucnaHez** [comment]
Еба, надо это починить, а то с убегающей сингой на слот вставать ну никак нельзя
